### ISSUE TITLE
Blazor 0.6?

### ISSUE THREAD

**Issue by gabrieldelaparra** [rpedretti/BlazorApp#2]
Hi, I am not being able to compile your solution. 
Nuget packages point to a Blazor 0.6.0 preview. 
Sorry if it is a noob question, how do you get those? or what do I have to do to compile your project?

**Comment by gabrieldelaparra** [comment]
I think that I found out.
https://dotnet.myget.org/gallery/blazor-dev

**Comment by gabrieldelaparra** [comment]
The solution was to add https://dotnet.myget.org/F/blazor-dev/api/v3/index.json to the package manager.

As reference:
https://www.c-sharpcorner.com/article/adding-package-source-in-visual-studio-2015/

**Comment by rpedretti** [comment]
Yes, that's it. Sorry for the delay to put the doc online. I'll try my best to do so at this weekend,

but for reference: https://github.com/aspnet/Blazor#using-ci-builds-of-blazor
